# 1. 프로젝트 계획 수립
https://www.notion.so/oreumi/DA-Mini-Project-9a2e11495fcb4181a5cff74eea53e2f7

# 2. Data 분석 및 결과 도출

## 2.1. 요구사항 분석

DA Mini Project
* 주제 : 온라인 학습 플랫폼 사용자 행동 패턴 분석
* 개요 :
```
이번 프로젝트는 학습 서비스를 이용하는 독자들 중 누가 서비스 구독을 연장할지 예측하기 위한 사전 파악에 초점을 맞추고 있습니다. 우리의 목표는 유저들의 학습 습관, 선호도, 이용 행태 등 다양한 측면을 면밀히 분석하는 것입니다.


이를 위해, 우리는 유저들의 학습 패턴, 서비스 이용 시간, 콘텐츠에 대한 반응, 그리고 이들이 얼마나 자주 서비스를 이용하는지 등 다양한 데이터를 수집하고 분석할 계획입니다. 이 데이터는 유저들이 서비스에 얼마나 만족하고 있는지, 어떤 요소들이 그들의 구독 결정에 영향을 미치는지 이해하는 데 중요한 역할을 할 것입니다.
```
* 데이터셋 : mini.csv
    * 메타데이터
        * user_id: 사용자의 고유 식별자
        * subscription_duration: 사용자가 서비스에 가입한 기간 (월)
        * recent_login_time: 사용자가 마지막으로 로그인한 시간 (일)
        * average_login_time:  사용자의 일반적인 로그인 시간
        * average_time_per_learning_session: 각 학습 세션에 소요된 평균 시간 (분)
        * monthly_active_learning_days: 월간 활동적인 학습 일수
        * total_completed_courses: 완료한 총 코스 수
        * recent_learning_achievement: 최근 학습 성취도
        * abandoned_learning_sessions: 중단된 학습 세션 수
        * community_engagement_level: 커뮤니티 참여도
        * preferred_difficulty_level: 선호하는 난이도
        * subscription_type: 구독 유형
        * customer_inquiry_history: 고객 문의 이력
        * payment_pattern : 사용자의 지난 3개월 간의 결제 패턴을 10진수로 표현한 값.
          - 7: 3개월 모두 결제함
          - 6: 첫 2개월은 결제했으나 마지막 달에는 결제하지 않음
          - 5: 첫 달과 마지막 달에 결제함
          - 4: 첫 달에만 결제함
          - 3: 마지막 2개월에 결제함
          - 2: 가운데 달에만 결제함
          - 1: 마지막 달에만 결제함
          - 0: 3개월 동안 결제하지 않음
        * target: 사용자가 다음 달에도 구독을 계속할지 (1) 또는 취소할지 (0)를 나타냄

## 2.2. Data Load 및 Column 분석

In [167]:
import pandas as pd

# Raw File load (11개 : 'data_info.csv' 제외.)
df_mini = pd.read_csv('./data/mini.csv')
df_done_detail = pd.read_csv('./data/done_detail.csv')
df_students_area_detail = pd.read_csv('./data/students_area_detail.csv')
df_user_data = pd.read_csv('./data/user_data.csv')
df_user_db = pd.read_csv('./data/user_db.csv')
df_user_db_ai = pd.read_csv('./data/user_db_ai.csv')
df_user_db_app = pd.read_csv('./data/user_db_app.csv')
df_access_detail = pd.read_csv('./data/access_detail.csv')
df_cohort_data = pd.read_csv('./data/cohort_data.csv')
df_user_registered_class = pd.read_csv('./data/user_registered_class.csv')
df_krx_data = pd.read_excel('./data/종목코드.xlsx')

In [168]:
# Raw File Print 1
df_mini.head()

,user_id,subscription_duration,recent_login_time,average_login_time,average_time_per_learning_session,monthly_active_learning_days,total_completed_courses,recent_learning_achievement,abandoned_learning_sessions,community_engagement_level,preferred_difficulty_level,subscription_type,customer_inquiry_history,payment_pattern,target
0,b919c29d,13,14,14.946163,8.427187,18,16,68.360455,3,4,Low,Basic,4,5,0
1,a0a60abb,16,18,18.453224,72.646087,16,13,97.567322,2,3,Medium,Basic,1,6,1
2,b9f171ae,22,1,16.195228,21.774492,13,14,94.358763,3,4,Medium,Premium,0,7,1
3,5dc0ba8b,1,19,17.628656,42.659066,19,18,70.153228,0,3,Low,Basic,1,0,1
4,65c83654,4,5,21.390656,30.744287,19,10,81.917908,2,4,Medium,Basic,3,0,1

In [169]:
# Raw File Print 2
df_done_detail.head()

                 lecture_id            done_date           user_id
0  5f266927e67b8fcf4340c08e  2020-08-07 12:02:16  78ff837c7cea9f33
1  5f266927e67b8fcf4340c08b   2020-08-08 1:14:59  2987aa87d23c9e3d
2  5f266927e67b8fcf4340c090  2020-08-17 17:10:49  23182525e9996864
3  5f35370cf9b9ed3dee7f1b72  2020-08-30 23:42:58  ffb6913842d617a5
4  5f35370cf9b9ed3dee7f1b6e  2020-08-25 16:56:15  2c6822e7e833dc95

In [170]:
# Raw File Print 3
df_students_area_detail.head()

                  lecture_id area   latitude   longitude           user_id
0   5f2cfa581c0c783e4e825379   부산  35.179554  129.075642  78ff837c7cea9f33
1   5f35370cf9b9ed3dee7f1b73   대전  36.348315  127.390594  2987aa87d23c9e3d
2  5f266927e67b8fcf4340c1464   서울  37.487935  126.857758  23182525e9996864
3   5f35370cf9b9ed3dee7f1b6a   부산  35.179554  129.075642  ffb6913842d617a5
4  5f266927e67b8fcf4340c1705   서울  37.487935  126.857758  2c6822e7e833dc95

In [171]:
# Raw File Print 4
df_user_data.head()

,_id,created_at,updated_at,name,marketing,managed,gender,age,progress_rate
0,e88cbf158991b41c,2022-08-26 10:04:54,2022-10-07 8:35:47,온아린,False,True,male,10,100.00
1,34525c4c113ea233,2021-02-20 1:23:38,2022-08-08 22:04:00,유강민,False,False,female,40,63.64
2,8f869d1ce7289b3d,2021-02-20 1:23:38,2022-08-08 22:04:00,문민서,False,False,female,30,63.64
3,bf1e94f981743e8d,2022-07-22 15:59:44,2022-08-29 21:12:15,석준영,False,False,male,50,64.77
4,b281c6fc121a338c,2022-07-22 15:59:44,2022-08-29 21:12:15,석도현,False,False,male,20,64.77

In [172]:
# Raw File Print 5
df_user_db.head()

            user_id gender area  age access_media  group  discounted
0  78ff837c7cea9f33      남  송파구   20        인스타그램      1     10000.0
1  2987aa87d23c9e3d      남  강서구   30           검색      1     30000.0
2  23182525e9996864      남  도봉구   20        인스타그램      1     20000.0
3  ffb6913842d617a5      여  용산구   20        인스타그램      1     20000.0
4  2c6822e7e833dc95      여  은평구   30          네이버      1     30000.0

In [173]:
# Raw File Print 6
df_user_db_ai.head()

            user_id gender area access_media     goal
0  9ba84e9cf8733ce6      남  강남구         페이스북  아이디어 실현
1  224bf36b191449c1      여   중구      오프라인 광고     문제해결
2  baf7aaf4e287ed86      여  광진구          네이버   부수입 창출
3  629ace9ab8ede18d      남  강서구         지인추천     의사결정
4  89ea14ec83acd6c2      남  관악구        인스타그램  아이디어 실현

In [174]:
# Raw File Print 7
df_user_db_app.head()

            user_id gender area  age access_media     goal
0  1a8adcf53f881ee8      남  송파구   20        인스타그램  아이디어 실현
1  bfd8847e1257757f      남  강서구   30           검색   부수입 창출
2  f4445dcb39d1bc54      남  도봉구   20        인스타그램   부수입 창출
3  75ac4eb719d64179      여  용산구   20        인스타그램     업무효율
4  f258561fb134f6fd      여  은평구   30          네이버     문제해결

In [175]:
# Raw File Print 8
df_access_detail.head()

                 lecture_id          access_date           user_id
0  5f266927e67b8fcf4340c087  2020-08-18 23:15:34  78ff837c7cea9f33
1  5f266927e67b8fcf4340c087  2020-08-04 11:56:07  2987aa87d23c9e3d
2  5f266927e67b8fcf4340c087  2020-08-03 12:19:58  23182525e9996864
3  5f266927e67b8fcf4340c087  2020-08-08 15:15:16  ffb6913842d617a5
4  5f266927e67b8fcf4340c087  2020-08-04 10:30:59  2c6822e7e833dc95

In [176]:
# Raw File Print 9
df_cohort_data.head()

    created_at           user_id name  progress_rate
0  2022. 8. 15  237a15a4c854a19f  이시우            100
1   2022. 8. 8  9e39ebcdb3e41fdb  경서희            100
2   2022. 8. 8  ccd9564adf22a5f7  지소희             36
3   2022. 8. 1  291ad78f3adfa9ee  최가은            100
4  2022. 8. 22  dfa8afb8ada36a4a  설서영            100

In [177]:
# Raw File Print 10
df_user_registered_class.head()

            user_id  web  app  sql  web.1
0  78ff837c7cea9f33    0    0    0    NaN
1  2987aa87d23c9e3d    0    0    0    NaN
2  23182525e9996864    1    1    1    NaN
3  ffb6913842d617a5    0    0    0    NaN
4  2c6822e7e833dc95    0    0    0    NaN

In [178]:
# Raw File Print 11
df_krx_data.head()

        종목명    종목코드
0      삼성전자    5930
1  LG에너지솔루션  373220
2    SK하이닉스     660
3     NAVER   35420
4  삼성바이오로직스  207940

## 2.3. Data 전처리
- 결측치 확인
- 데이터 타입 변환
- 중복, 이상치 분석 및 처리
- 통계 분포 확인 (평균, 중간값 등)

## 2.4. Data 탐색 분석 및 시각화
- 타겟(구독 여부) 사용자 분포 확인
- 구독 유지 vs 취소 특징 비교
- 특성 간 상관관계 분석 : 특성(학습 시간, 성취도, 결제 패턴 등)이 구독 여부에 미치는 영향

## 2.5. 결과 도출

# 3. 발표 자료 제작

## 3.1. 구성 고민
- Tool
- 페이지 구성 및 배치

## 3.2. 제작

## 3.3. 최종 정리
- 불필요한 내용 정리
- 발표 시간 검토